name: Build Neon Dash APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Install system dependencies
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3-dev \
            python3-pip \
            git \
            openjdk-17-jdk \
            unzip \
            zip \
            libncurses5-dev \
            libncurses6 \
            libstdc++6 \
            zlib1g-dev \
            libssl-dev \
            libffi-dev \
            autoconf \
            automake \
            cmake \
            pkg-config

      # 3. Install Android SDK + Build-tools + NDK
      - name: Install Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip
          # Fix folder structure (Google expects "latest/")
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ || true
          
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "ndk;25.1.8937393"

      # 4. Install Buildozer
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      # 5. Build the APK
      - name: Build APK with Buildozer
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export ANDROIDNDK=$HOME/android-sdk/ndk/25.1.8937393
          buildozer android debug

      # 6. Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeonDash-Android
          path: bin/*.apk
