name: Build Neon Dash APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            libssl-dev \
            libffi-dev \
            libglu1-mesa \
            libgles2-mesa-dev \
            libncurses5 \
            libtinfo6

      - name: Install Buildozer & Cython
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Install Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ || true

          # Accept licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses

          # Install required Android tools
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "ndk;25.1.8937393"

          # Force install build-tools 33.0.2 (contains aidl)
          wget https://dl.google.com/android/repository/build-tools_r33.0.2-linux.zip -O build-tools.zip
          unzip build-tools.zip -d $HOME/android-sdk/
          mv $HOME/android-sdk/android-13 $HOME/android-sdk/build-tools/33.0.2 || true

          # Add everything to PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

          # Debug check for aidl
          ls -l $HOME/android-sdk/build-tools/33.0.2/aidl || true

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NeonDash-APK
          path: bin/*.apk
