name: Build Neon Dash APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install system dependencies for buildozer
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3-dev \
            python3-pip \
            git \
            openjdk-17-jdk \
            unzip \
            zip \
            libncurses5-dev \
            libstdc++6 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libblas-dev \
            liblapack-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-tools \
            libmtdev-dev \
            autoconf \
            libtool \
            pkg-config \
            cmake

      # Install buildozer
      - name: Install buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      # Initialize buildozer (if no spec file exists)
      - name: Initialize buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # Build APK
      - name: Build release APK
        run: |
          buildozer -v android debug

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeonDash-Android
          path: bin/*.apk
