name: Build Neon Dash

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Build executable
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile neon_dash.py
        shell: cmd

      # Upload build artifact
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: NeonDash-${{ github.run_number }}
          path: dist/neon_dash.exe
